.gitignore, README.md, src/main/kotlin/com/beust/klaxon/DSL.kt, src/main/kotlin/com/beust/klaxon/Json.kt, src/main/kotlin/com/beust/klaxon/Lookup.kt, src/test/kotlin/com/beust/klaxon/KlaxonTest.kt
- Added few tests
- Introduced lookup operation to search by JSON like this
```kotlin
json.lookup("system.users.name")
```
=> Lookup function

README.md, build.gradle, klaxon.iml, pom.xml, src/main/kotlin/com/beust/klaxon/DSL.kt, src/main/kotlin/com/beust/klaxon/Lexer.kt, src/main/kotlin/com/beust/klaxon/Lookup.kt, src/main/kotlin/com/beust/klaxon/Parser.kt, src/main/kotlin/com/beust/klaxon/Render.kt, src/main/kotlin/com/beust/klaxon/Status.kt, src/test/kotlin/com/beust/klaxon/KlaxonTest.kt, src/test/resources/escaped.json
Requires PR #6  to be merged before
=> Pretty print + string escape

build.gradle, klaxon.iml, src/main/kotlin/com/beust/klaxon/Lookup.kt, src/test/kotlin/com/beust/klaxon/TestRFC7159.kt
=> Update to m14

src/main/kotlin/com/beust/klaxon/Render.kt
=> fixes map rendering, issue #24

build.gradle, gradle/wrapper/gradle-wrapper.properties, kobalt/src/Build.kt
Update to Kotlin 1.0 with small fixes and set the last version to 0.24
=> Update to kotlin 1.0

README.md
@cbeust could you push the 0.24 to jcenter? :)
=> Update to 0.24 and change arrayListOf to listOf

README.md
~~Also separated the `group`/`name`/`version` parts~~
=> Updated reference in readme to latest version

README.md
It was breaking the highlighting.
=> Remove extra double quote

src/main/kotlin/com/beust/klaxon/Render.kt
=> escapeString should escape ‘

src/main/kotlin/com/beust/klaxon/JsonReader.kt, src/test/kotlin/com/beust/klaxon/StreamingTest.kt
This also include relevant test
=> Supported streaming arrays inside objects (and other nestings)

README.md
I'm happy to adjust as needed if the wording or level of detail is not ideal.
=> Add note regarding caveat of streaming API.  Addresses issue #115

src/main/kotlin/com/beust/klaxon/JsonReader.kt, src/test/kotlin/com/beust/klaxon/StreamingTest.kt
=> Fixes #138: Adds nextDouble to JsonReader

src/main/kotlin/com/beust/klaxon/Lexer.kt
=> Throw KlaxonException instead of RuntimeException

src/main/kotlin/com/beust/klaxon/JsonReader.kt, src/main/kotlin/com/beust/klaxon/KlaxonException.kt, src/test/kotlin/com/beust/klaxon/StreamingTest.kt
=> Don't convert values in nextString() and standardize wrong type exception

build.gradle, src/main/kotlin/com/beust/klaxon/JsonReader.kt, src/test/kotlin/com/beust/klaxon/StreamingTest.kt
Fixes #142 
Also:
- Updates Gradle build to match Kobalt
- Cleans up test cases in `StreamingTest`
=> Add nextLong() and nextBigInteger()

build.gradle, kobalt/src/Build.kt, src/main/kotlin/com/beust/klaxon/JsonObjectConverter.kt, src/test/kotlin/com/beust/klaxon/Issue169.kt
This pull request resolve the bug in #169 and updates Kotlin to the latest version.
=> Resolution of #169

README.md
Found a few broken links in the README due to a structural change in the repo.
=> Fix links to source in README.

klaxon/src/main/kotlin/com/beust/klaxon/DefaultConverter.kt, klaxon/src/test/kotlin/com/beust/klaxon/Issue237Test.kt
Here is the PR suggested in issue #237, including a test for it.
Cheers,
Alfonso
=> Fixes for issue #237

klaxon-root.gradle.kts
=> [SECURITY] Download Dependencies over HTTPS

klaxon/src/main/kotlin/com/beust/klaxon/EnumConverter.kt, testing/tests/src/test/kotlin/com/beust/klaxon/KlaxonTest.kt
=> Allow renaming enum values with the Json annotation

klaxon/src/main/kotlin/com/beust/klaxon/JsonObject.kt, klaxon/src/test/kotlin/com/beust/klaxon/Issue340Test.kt
Just containing those changes + Unit test
=> Followup3: JsonObject: allow any data type as key
