build.gradle
klaxon.iml
src/main/kotlin/com/beust/klaxon/Lookup.kt
src/test/kotlin/com/beust/klaxon/KlaxonTest.kt

We have `mapChildren` nullability issue. 
In the original `mapChildren` declaration we have `<T>` that could be both `T` and `T?` and it only depends on `block` function return type so if we have `block` that returns non-nullable type then `mapChildren` will return JsonArray of non-nullable type too that is not true as we have `null` for non-object array elements.
Also notice that this nullability issue is not discovered by Kotlin M12 but in M13 nullability checks was improved and compilation fails with current master snapshot because of unsafety. 
This pull request provides fix: `mapChildren` now always returns nullable type and also there is `mapChildrenObjectsOnly` that skips non-object members and produces no nulls in the result JsonObject so returns non-nullable `T`
Notice it is a …

mapChildren nullability issue

---

.gitignore
build.gradle
kobalt/src/Build.kt
kobalt/wrapper/kobalt-wrapper.properties

This PR updates:
- kotlin to beta4 (4584)
- kobalt to 0.369
- .gitignore to ignore .kobalt folder
- klaxon version to 0.21
Could you push the update to jcenter?
Thanks

Update to beta4 4584

---

src/main/kotlin/com/beust/klaxon/Lexer.kt
src/test/kotlin/com/beust/klaxon/TestLexerInputSize.kt
src/test/kotlin/com/beust/klaxon/TestRFC7159.kt
src/test/kotlin/com/beust/klaxon/TestTypes.kt
src/test/resources/types.json

Also some improvements in Lexer:
* support Charset selection;
* do not read all input fully into memory;
* fix Unicode characters parsing.
Contains fix for #19

Fix Unicode support

---

src/main/kotlin/com/beust/klaxon/Lexer.kt
src/main/kotlin/com/beust/klaxon/Parser.kt

And also `charset` parameter added to `Parser#parse(InputStream)` so user would able to specify correct encoding if it's not UTF-8.

Add support for `java.io.Raeder` in Parser API

---

src/main/kotlin/com/beust/klaxon/Render.kt
src/test/kotlin/com/beust/klaxon/KlaxonTest.kt

**Issue**: klaxon automatically converts all members of a list to string
```kotlin
val input = listOf(null, 1, 2, 3)
valueToString(input)    // return ["null","1","2","3"] instead of [null,1,2,3]
```

fixes list rendering

---

build.gradle
src/main/kotlin/com/beust/klaxon/DSL.kt
src/main/kotlin/com/beust/klaxon/Render.kt
src/test/kotlin/com/beust/klaxon/KlaxonTest.kt

As mentioned in #48, it would be cool to have canonical json, for example to use signatures over json that would otherwise be formatted different by every library used. [This ietf draft](https://www.ietf.org/archive/id/draft-staykov-hu-json-canonical-form-00.txt) elaborates more on canonical json.
I have implemented the canonical json as an opt-in in the `JsonBase.toJsonString()` method. The changes are:
- If `canonical` is true, the value of `prettyPrint` is ignored because canonical json requires to remove all redundant whitespaces
- If `canonical` is true, the map of every `JsonObject` is sorted before serialization
- If `canonical` is true, doubles (and floats) are always formatted in scientific form, like `1.234E2` and never like `123.4`

Add canonical json output to toJsonString() method

---

README.md
src/main/kotlin/com/beust/klaxon/Render.kt

1. correct a function name: `isPrintableUnicode()` -> `isNotPrintableUnicode()`
2. improve readability with kotlin operator `(c >= MIN && c <= MAX)` can be replaced with `c in MIN..MAX`

correct a function name, improve readability. Also update/fixed bugs in example

---

src/main/kotlin/com/beust/klaxon/Lexer.kt

**issue**
`Parser.parse(StringBuilder("[flse]"))` throws exception.
> Exception in thread "main" java.lang.RuntimeException: Unexpected character at position 6: 'e (101)'
But the actual position of 'e' is 5 (or 4 if 0-based).

Fix error position

---

src/main/kotlin/com/beust/klaxon/DefaultConverter.kt
src/test/kotlin/com/beust/klaxon/BindingTest.kt

The "convertValue" fun of DefaultConverter now converts JsonObjects using klaxon.fromJsonObject. Added tests for recursive object binding.
Since I'm new to Kotlin and not very experienced in Java, I hope everything is okay.

Recursive object binding in high level API.

---

README.md

I get the following message
> Configuration 'compile' is obsolete and has been replaced with 'implementation'. It will be removed at the end of 2018
According to [this SO answer](https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-and-compile-in-gradle), it's safe to replace for `implementation`

Compile -> implementation

---

src/main/kotlin/com/beust/klaxon/DefaultConverter.kt
src/test/kotlin/com/beust/klaxon/Serialization.kt
src/test/kotlin/com/beust/klaxon/SerializationTest.kt

Hello ! 
Apparently, I found a bug in Float serialization.
I use _data class_ in my code to store _Settings_ with Float variables inside. For example consider the following: 
```
data class Settings(val text: String, val volume: Float)
```
Then I write my _Settings_ object with _Klaxon_, and read it. While reading the file I get an exception: _"Couldn't find a suitable constructor <...>: java.lang.IllegalArgumentException argument type mismatch"_. With Doubles instead of Floats it's work like a charm.
Here is code snippet:
```
val settings = Settings("ducks", 0.55f)
val klaxon = Klaxon()
val jsonString = klaxon.toJsonString(settings)
// "{"text" : "ducks", "volume": "0.55f"}"
val jsonObject = klaxon.parse<Settings>(jsonString)
// Exception here
```
From what I understood debugging this …

Float serialization

---

src/main/java/com/beust/klaxon/Json.kt
src/main/kotlin/com/beust/klaxon/DefaultConverter.kt
src/main/kotlin/com/beust/klaxon/JsonObjectConverter.kt
src/test/kotlin/com/beust/klaxon/ParseFromEmptyNameTest.kt

Fixes #146 
Technically, this is no different from empty string. It is still a valid JSON key that could theoretically be used. However, it is significant less likely to be used.

Change default value for anotation name parameter

---

klaxon/src/main/kotlin/com/beust/klaxon/KlaxonJson.kt

This makes it so that you can expand the capabilities of the `KlaxonJson` interface with your own custom wrapper types.

Makes KlaxonJson an interface

---

README.md

Provide the correct / updated path for the PathMatcher interface, instead of a link that returns a 404 - Not Found.

Fix path for PathMatcher in Readme file

---

.travis.yml
klaxon-root.gradle.kts

This doesn't actually fix the tests, this just improves logging in travis and when running the gradle tests.

Improve the readability of the output of the gradle and travis logs

---

klaxon/src/main/kotlin/com/beust/klaxon/JsonObject.kt
testing/test-resources/src/main/resources/escaped.json
testing/tests/src/test/kotlin/com/beust/klaxon/KlaxonTest.kt
testing/tests/src/test/kotlin/com/beust/klaxon/TestTypes.kt

```
$ python
>>> print(json.dumps({'"':1}))
{"\"": 1}
```
In Klaxon we get `{""": 1}` instead of `{"\"": 1}`, which is obviously wrong.
Changed `escape.json` and the escaping tests and fixed the code.

strings should be escaped in keys too

---

klaxon/src/main/kotlin/com/beust/klaxon/JsonReader.kt
klaxon/src/main/kotlin/com/beust/klaxon/KlaxonParser.kt
klaxon/src/main/kotlin/com/beust/klaxon/Lexer.kt
klaxon/src/main/kotlin/com/beust/klaxon/StateMachine.kt
klaxon/src/main/kotlin/com/beust/klaxon/token/Token.kt
klaxon/src/test/kotlin/com/beust/klaxon/LexerTest.kt

Overview:
Taking advantage of a very handy Kotlin feature, sealed classes, Tokens can now be used both as a type and as data. This makes the TokenType enum class redundant.
Every kind of Token is now its own object/class, making it much easier to distinguish between tokens (instead of trying to cast from Any? everywhere), simplifying parsing methods and the production of Tokens.
Main changes:
Token.kt: New file containing the Token sealed class and its inherited objects, as well as a tokenType property which simply returns 'this' as a TokenType alias (in case of Value, returns a singleton version of Value).
Lexer.kt: Remove all uses of TokenType and just create the appropriate Token in actualNextToken(). Kotlinify some methods.
JsonReader.kt: Make consumeToken() generic (inline reified), …

Change Token to sealed class. Simplify all uses of Tokens

---

klaxon/src/main/kotlin/com/beust/klaxon/DefaultConverter.kt
klaxon/src/test/kotlin/com/beust/klaxon/Issue253Test.kt

Prevent DefaultConverter from skipping attributes with null values when encoding.
Also includes a test to make sure the issue is and stays solved.

Encode attributes with null values #253

---

klaxon/src/main/kotlin/com/beust/klaxon/Klaxon.kt

This PR calls `use` on all `FileReader` Klaxon creates from files given to it by the user.
Klaxon should close a `FileReader` if it opens one to prevent issues when a user tries to delete a file they previously gave to Klaxon.
None.
I'm not sure how I could go about testing this, but this is a simple change and I have been using this fix in my own code.
Closes #259.

Call use on FileReaders Klaxon creates

---

klaxon/src/main/kotlin/com/beust/klaxon/JsonObjectConverter.kt
klaxon/src/test/kotlin/com/beust/klaxon/ParseObjectTest.kt

In the event that a user wants to parse into an object, no constructor will be found, so `result` will be `null` inside `initIntoUserClass`. This PR tries to parse `concreteClass` into an object instance if parsing into a normal class instance fails.

Parse into object instance if constructor parsing fails

---

README.md

* Changes 'instantiate' to 'classFor' in example code for polymorphic
fields
This example code looks to be incorrect and doesn't compile. I believe this is supposed to be similar to the previous example on polymorphic classes, whereas the overridden function is `classFor` instead of `instantiate` 😊
```
class ShapeTypeAdapter: TypeAdapter<Shape> {
override fun instantiate(type: Any): KClass<out Shape> = when(type as Int) {
1 -> Rectangle::class
2 -> Circle::class
else -> throw IllegalArgumentException("Unknown type: $type")
}
}
```

Add correction to README

---

README.md
klaxon/src/main/java/com/beust/klaxon/Json.kt
klaxon/src/main/kotlin/com/beust/klaxon/DefaultConverter.kt
klaxon/src/main/kotlin/com/beust/klaxon/JsonObjectConverter.kt
klaxon/src/test/kotlin/com/beust/klaxon/JsonAnnotationTest.kt

This allows a property to be made absent in the serialized JSON by setting its value to null. The default remains to make properties with value null present in the JSON as `"name" : null`.
To achieve this, a new attribute called `serializeNull` is added to the `@Json` annotation. When `serializeNull = false` is set, Kotlin default values will be ignored during parsing. 
Tests and Documentation are included. 
This feature was requested in https://github.com/cbeust/klaxon/issues/253#issuecomment-525353792 (and I would like it, too). 
A remaining question: What about the performance hit due to additional checks during parsing/serialization? Should I benchmark? Is it likely to be relevant? What is your stance regarding performance?

Allow Property to be Absent in JSON when Value is Null

---

klaxon/src/main/kotlin/com/beust/klaxon/KlaxonParser.kt
klaxon/src/main/kotlin/com/beust/klaxon/Lexer.kt
klaxon/src/test/kotlin/com/beust/klaxon/JazzerTest.kt

I ran the JVM fuzzer [Jazzer](https://github.com/CodeIntelligenceTesting/jazzer) on Klaxon's default JSON parser and got four distinct crashes with exceptions not derived from `KlaxonException`.
Every commit in this PR addresses the root cause of one these crashes and adds a test case with the respective Jazzer finding.

Fix unexpected exceptions

---

klaxon/src/main/java/com/beust/klaxon/TypeFor.kt
klaxon/src/main/kotlin/com/beust/klaxon/JsonObjectConverter.kt
klaxon/src/test/kotlin/com/beust/klaxon/TypeAdapterTest.kt

This is a proposed patch for [issue 353](https://github.com/cbeust/klaxon/issues/353).

adding null support for type adapters w/ back compatibility

---

README.md
klaxon/src/main/kotlin/com/beust/klaxon/DefaultConverter.kt
klaxon/src/main/kotlin/com/beust/klaxon/JsonObjectConverter.kt
klaxon/src/main/kotlin/com/beust/klaxon/Klaxon.kt
klaxon/src/main/kotlin/com/beust/klaxon/KlaxonSettings.kt
klaxon/src/test/kotlin/com/beust/klaxon/InstanceSettingsTest.kt

This pull request adds the ability to optionally supply settings for a Klaxon instance in the constructor. These instance wide settings complement the settings of individual attributes set with `@Json(...)`.
```kotlin
val settings = KlaxonSettings(serializeNull = false)
```
Currently, it is only implemented for `serializeNull`, however, it is simple to extend for future uses too.
This allows to e.g. write:
```kotlin
data class User(
val username: String, val email: String, // mandatory
val phone: String?, val fax: String?, val age: Int? // optional
)
Klaxon(settings)
.toJsonString(User("user", "user@example.org", null, null, null))
// displays {}
```
instead of having to add these options to every attribute like this:
```kotlin
data class User(
val username: String, val email: String, // …
```

#344 Add instance-wide settings
